#!/bin/bash

[[ -z $1 ]] && echo \$1, \$2 are required. && exit 1;

header=$(echo -e "/* This file is auto-generated by gen_const_data.sh */
#include \"ast/tokens.h\"

const char *STRING_TOKENS[TOK_DUMMY_LAST] = {")

toks=$(cat $1 |
    grep -e "^ \+TOK" |
    head -n-1 |
    perl -gnpE 's/(\w+),.*/"\1",/g')

echo -e "$header\n$toks\n};" > $2
